---
title: "Parents Make the Difference"
output:
  html_document:
    toc: false
    toc_float: false
bibliography: parenting.bib
csl: vancouver.csl
---

*The International Rescue Committee and researchers from Duke University have collaborated on two randomized evaluations of Parents Make the Difference, a group-based parenting skills intervention to decrease child maltreatment and improve parent-child interactions-thereby helping children to reach their developmental potential. We evaluated the intervention in Liberia, a conflict-affected and low-resource setting. The purpose of this study website is to store all study-related products and data (licensed under the [CC-BY license](https://creativecommons.org/licenses/by/4.0/)). New material will be released as academic manuscripts enter production.*

* * * 

In low- and middle-income countries, 250 million children under 5 years old are at risk for not reaching their developmental potential [@black:2017]. For most of these children, this is not due to one isolated risk factor but rather to risk factors that accumulate, or pile up, over these first important years of life. These include physical health problems, lack of basic needs due to extreme poverty, and violence at community and family levels, among  others. 

What do these children need? A life course conceptual framework outlined by Black et al. (2017) first proposed the protective conditions of a stable social, cultural, and economic context coupled with access to needed services and resources. Lastly, they assert the importance of nurturing care through responsive caregiving practices that promote health, nutrition, safety, and early learning. Improving nurturing care is the central goals of the *Parents Make the Difference* intervention developed and evaluated in the studies presented here. 

One major threat to effective caregiving is the excessive use of harsh discipline-both physical and verbal-that can have lasting negative impacts on child development [@cowell:2015;@walker:2011;@repetti:2002]. Risk for these types of maltreatment seems to be higher for children in low-resource and conflict-affected settings, in which families face a wide range of stressors including displacement, separation, grief, poverty, and limited educational and employment opportunities [@borba:2016; @mels:2010; @reed:2012]. Given this, decreasing harsh treatment-and replacing it with positive behavior management strategies-is a primary, specific target of *Parents Make the Difference*, or PMD. 

We have conducted two randomized trials to evaluate the impact of PMD, with the second building on results of the first. In Study 1, we evaluated PMD with 270 caregivers in a rural area of Liberia, finding that the program decreased caregivers' use of harsh discipline and increased positive interactions with their children. However, we did not see direct impacts on the children's wellbeing. Based on these results, we wanted to boost the intervention effects and revised the intervention to increase use of evidence-based strategies, including active practice and learning in sessions. We also developed a home visiting protocol to provide individualized skills coaching to caregivers. To test the revised intervention, we conducted a second study that was larger and allowed for longer follow-up-this time in Monrovia, an urban setting. This ongoing trial includes more than 800 caregivers divided into three groups. Some caregivers received the group PMD sessions only, some received the PMD sessions plus home visits, and others were in a waitlist control group. Results expected in late 2018.

# References