---
title: "Presentations"
output:
  html_document:
    toc: false
    toc_float: false
bibliography: parenting.bib
csl: vancouver.csl
---
<br>

### Presentation at the 2018 National Parenting Conference, Monrovia, Liberia
Puffer, E.S, Green, E.P., Chase, R., Zayzay, J., & Finnegan, A. (2018, June). *Parents Make the Difference research results*. Paper presented at the National Parenting Conference, Monrovia, Liberia. **[slide deck, [research brief](https://github.com/ericpgreen/pmd/raw/master/data%20and%20replication%20files/resources/PMD%20Conference%20June%202018%20Research%20Brief.pdf)]**

### Presentation at the 39th Annual Meeting and Scientific Sessions of the Society of Behavioral Medicine

Puffer, E. S., Green, E. P., Chase, R. M., & Sim, A. (2018). *Associations between parenting behaviors and children’s social-emotional, behavioral, and cognitive well-being in Liberia*. Oral presentation at the 39th Annual Meeting and Scientific Sessions of the Society of Behavioral Medicine, New Orleans, LA.

### Presentation at the 30th Annual Meeting of the International Society of Traumatic Stress Studies

Puffer, E. S., Green, E. P., Chase, R. M., Friis, E., Sim, A. L., Garcia-Rolland, E., & Boone, L. (2014). *The Parents Make the Difference program in Liberia: Results from a randomized controlled trial*. Oral presentation at the International Society of Traumatic Stress Studies 30th Annual Meeting, Miami, FL.

